import type {
  AuditEntry,
  IndexStatus,
  Mastercard,
  OllamaStatus,
  OnFloorRecord,
  RecoveryRecord,
  ValidationResult,
} from "./types";

// Naming conventions and folder shapes mirror what's actually in the real
// I:\Department Files\Molding\Molding Mastercards indexed data (Stage 1 of
// the companion Python app) -- kept realistic rather than invented.

export const mockMastercards: Mastercard[] = [
  {
    id: "mc-1",
    partNumber: "9817030",
    moldBaseNumber: "93",
    machineNumber: "102",
    material: "PVC Gray",
    processDate: "2026-06-12",
    sourceFolder: "Molding Mastercards\\IMM 102",
    fileType: "xlsx",
    filePath: "I:\\Department Files\\Molding\\Molding Mastercards\\IMM 102\\9817030_MA102_MB93.xlsx",
    matchType: "Exact",
    validationStatus: "PASS",
    printedStatus: true,
    loggedStatus: true,
    modifiedDate: "2026-06-12T09:14:00",
  },
  {
    id: "mc-2",
    partNumber: "9817030",
    moldBaseNumber: "93",
    machineNumber: "104",
    material: "PVC Gray",
    processDate: "2026-05-30",
    sourceFolder: "Molding Mastercards\\IMM 104",
    fileType: "xlsx",
    filePath: "I:\\Department Files\\Molding\\Molding Mastercards\\IMM 104\\9817030_MA104_MB93.xlsx",
    matchType: "Comparable",
    validationStatus: "PASS",
    printedStatus: false,
    loggedStatus: false,
    modifiedDate: "2026-05-30T14:02:00",
  },
  {
    id: "mc-3",
    partNumber: "37R654080",
    moldBaseNumber: "562",
    machineNumber: "210",
    material: "PPFR Black",
    processDate: "2026-07-01",
    sourceFolder: "Molding Mastercards\\IMM 210",
    fileType: "xlsx",
    filePath: "I:\\Department Files\\Molding\\Molding Mastercards\\IMM 210\\37R654080_MA210_MB562.xlsx",
    matchType: "Exact",
    validationStatus: "WARNING",
    printedStatus: false,
    loggedStatus: false,
    modifiedDate: "2026-07-01T08:45:00",
  },
  {
    id: "mc-4",
    partNumber: "37A663006",
    moldBaseNumber: "93",
    machineNumber: "102",
    material: "POM Black",
    processDate: "2026-07-16",
    sourceFolder: "Molding Mastercards\\IMM 102",
    fileType: "xls",
    filePath: "I:\\Department Files\\Molding\\Molding Mastercards\\IMM 102\\37A663006_MA102_MB93 180MM SCREW 2.xls",
    matchType: "Exact",
    validationStatus: "FAIL",
    printedStatus: false,
    loggedStatus: false,
    modifiedDate: "2026-07-16T10:54:00",
  },
  {
    id: "mc-5",
    partNumber: "373662301",
    moldBaseNumber: "786",
    machineNumber: "913",
    material: "CPVC White",
    processDate: "2026-06-22",
    sourceFolder: "Process Engineering folder NTQs\\Engineer setups folder",
    fileType: "xlsx",
    filePath:
      "I:\\Department Files\\Molding\\Process Engineering folder NTQs\\Engineer setups folder\\373662301_MA913_MB786.xlsx",
    matchType: "Process Sheet",
    validationStatus: "unknown",
    printedStatus: false,
    loggedStatus: false,
    modifiedDate: "2026-06-22T11:10:00",
  },
  {
    id: "mc-6",
    partNumber: "9839-249NF",
    moldBaseNumber: "650",
    machineNumber: "209",
    material: "PP White",
    processDate: "2026-07-18",
    sourceFolder: "Molding Mastercards\\IMM 209",
    fileType: "xlsx",
    filePath: "I:\\Department Files\\Molding\\Molding Mastercards\\IMM 209\\9839-249NF_MA209_MB650.xlsx",
    matchType: "Exact",
    validationStatus: "PASS",
    printedStatus: true,
    loggedStatus: false,
    modifiedDate: "2026-07-18T13:29:00",
  },
  {
    id: "mc-7",
    partNumber: "379801040",
    moldBaseNumber: "741",
    machineNumber: "303",
    material: "PVDF Natural",
    processDate: "2026-04-09",
    sourceFolder: "Molding Mastercards\\IMM 303",
    fileType: "xls",
    filePath: "I:\\Department Files\\Molding\\Molding Mastercards\\IMM 303\\379801040_MA303_MB741 VICTAULIC.xls",
    matchType: "Multiple",
    validationStatus: "PASS",
    printedStatus: false,
    loggedStatus: false,
    modifiedDate: "2026-04-09T15:41:00",
  },
  {
    id: "mc-8",
    partNumber: "9878020BR",
    moldBaseNumber: "721",
    machineNumber: "210",
    material: "HDPE Black",
    processDate: "2026-07-20",
    sourceFolder: "Molding Mastercards\\New_Mastercards_Intern\\ReadyToPrint",
    fileType: "xlsx",
    filePath:
      "I:\\Department Files\\Molding\\Molding Mastercards\\New_Mastercards_Intern\\ReadyToPrint\\9878020BR_MA210_MB721.xlsx",
    matchType: "Exact",
    validationStatus: "PASS",
    printedStatus: true,
    loggedStatus: true,
    modifiedDate: "2026-07-20T16:03:00",
  },
  {
    id: "mc-9",
    partNumber: "802-015NF",
    moldBaseNumber: "607",
    machineNumber: "103",
    material: "ABS Natural",
    processDate: "",
    sourceFolder: "Process Engineering folder NTQs\\Engineer setups folder",
    fileType: "pdf",
    filePath:
      "I:\\Department Files\\Molding\\Process Engineering folder NTQs\\Engineer setups folder\\802-015NF_MA103_MB607.pdf",
    matchType: "Missing",
    validationStatus: "unknown",
    printedStatus: false,
    loggedStatus: false,
    modifiedDate: "2026-03-11T09:00:00",
  },
  {
    id: "mc-10",
    partNumber: "9801040",
    moldBaseNumber: "665",
    machineNumber: "512",
    material: "PET Clear",
    processDate: "2026-06-05",
    sourceFolder: "Molding Mastercards\\IMM 512",
    fileType: "xlsx",
    filePath: "I:\\Department Files\\Molding\\Molding Mastercards\\IMM 512\\9801040_MA512_MB665.xlsx",
    matchType: "Exact",
    validationStatus: "PASS",
    printedStatus: false,
    loggedStatus: false,
    modifiedDate: "2026-06-05T10:22:00",
  },
];

export const mockValidationResults: Record<string, ValidationResult> = {
  "mc-1": {
    id: "val-1",
    mastercardId: "mc-1",
    overall: "PASS",
    printingBlocked: false,
    timestamp: "2026-07-29T08:10:00",
    rules: [
      {
        ruleId: "PART_MOLD_MACHINE_CONSISTENCY",
        worksheet: "Repro",
        cell: "C3",
        currentValue: "9817030 / MB93 / MA102",
        explanation: "Part, mold, and machine on the Repro sheet match the filename and card body.",
        severity: "PASS",
        printingBlocked: false,
      },
    ],
  },
  "mc-3": {
    id: "val-3",
    mastercardId: "mc-3",
    overall: "WARNING",
    printingBlocked: false,
    timestamp: "2026-07-29T08:12:00",
    rules: [
      {
        ruleId: "PROC_DATE_MISSING_OR_CHANGED",
        worksheet: "Form",
        cell: "G8",
        currentValue: "(blank)",
        explanation: "Proc Date is blank. Confirm this is intentional before printing.",
        severity: "WARNING",
        printingBlocked: false,
      },
    ],
  },
  "mc-4": {
    id: "val-4",
    mastercardId: "mc-4",
    overall: "FAIL",
    printingBlocked: true,
    timestamp: "2026-07-29T08:15:00",
    rules: [
      {
        ruleId: "REF_ERROR",
        worksheet: "Repro",
        cell: "J12",
        currentValue: "#REF!",
        explanation: "Broken cell reference found on the Repro sheet. Printing is blocked until this is fixed in the source workbook.",
        severity: "FAIL",
        printingBlocked: true,
      },
      {
        ruleId: "CELCON_BLACK_ZERO",
        worksheet: "Form",
        cell: "G6",
        currentValue: "0",
        explanation: "Celcon Black material field reads 0 -- likely a conversion error, not a real process value.",
        severity: "FAIL",
        printingBlocked: true,
      },
    ],
  },
};

export const mockOnFloorRecords: OnFloorRecord[] = [
  { id: "of-1", mastercard: mockMastercards[0], datePrinted: "2026-06-12T09:20:00", logStatus: "Logged", matchedRow: true },
  { id: "of-2", mastercard: mockMastercards[5], datePrinted: "2026-07-18T13:35:00", logStatus: "Unlogged", matchedRow: false },
  { id: "of-3", mastercard: mockMastercards[7], datePrinted: "2026-07-20T16:10:00", logStatus: "Logged", matchedRow: true },
];

export const mockRecoveryRecords: RecoveryRecord[] = [
  {
    id: "rec-1",
    mastercard: mockMastercards[5],
    failureReason: "OnFloor workbook was locked (open by another user) when the log write was attempted.",
    savedAt: "2026-07-18T13:36:12",
    retried: false,
  },
];

export const mockAuditHistory: AuditEntry[] = [
  {
    id: "audit-1",
    timestamp: "2026-07-29T07:58:00",
    userRequest: "Does part 9817030 exist?",
    toolSelected: "find_mastercard",
    file: "9817030_MA102_MB93.xlsx",
    validationResult: "n/a",
    printAction: "none",
    loggingAction: "none",
    outcome: "Success",
  },
  {
    id: "audit-2",
    timestamp: "2026-07-29T08:15:20",
    userRequest: "Validate this Mastercard.",
    toolSelected: "validate_mastercard",
    file: "37A663006_MA102_MB93 180MM SCREW 2.xls",
    validationResult: "FAIL",
    printAction: "none",
    loggingAction: "none",
    outcome: "Blocked",
  },
  {
    id: "audit-3",
    timestamp: "2026-07-18T13:34:50",
    userRequest: "Print this Mastercard.",
    toolSelected: "confirm_print",
    file: "9839-249NF_MA209_MB650.xlsx",
    validationResult: "PASS",
    printAction: "Print command accepted",
    loggingAction: "Failed -- workbook locked, saved to recovery queue",
    outcome: "Failed",
  },
];

export const mockIndexStatus: IndexStatus = {
  fileCount: 6451,
  lastUpdated: "2026-07-29T16:48:46",
  stale: false,
  staleReason: "",
};

export const mockOllamaStatus: OllamaStatus = {
  connected: true,
  model: "qwen3.5:9b",
  host: "http://localhost:11434",
};
